BEGIN TRAN
UPDATE S
SET S.RENDA = T.Liquido_OK
FROM [FUNCIONARIOS_PUBLICOS_MUNICIPAIS_202509].[dbo].[SERVIDORES_MUNICIPAIS_CONSOLIDADO] AS S
INNER JOIN [FUNCIONARIOS_PUBLICOS_MUNICIPAIS_202509].[dbo].[RR_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_BOAVISTA_TEMP] AS T
    ON S.NOME_TRATADO = T.NOME
WHERE S.ID_ORIGEM = 31
  AND S.CPF_INCOMPLETO IS NULL;