--PELO NOME
UPDATE B
SET
B.RENDA_BENEFICIO = A.RENDA,
B.NOME_BENEFICIO = A.NOME_BENEFICIO,
B.DATA_PGTO_BENEFICIO = A.MÊS_COMPETÊNCIA
 FROM [TEMP_VANDERLAN].[dbo].[CVP_POC Resolução CNSP 473_RENDA_v3-Dxon] B 
INNER JOIN LOAS_BPC.dbo.NOVO_202512_BPC_E_OUTROS A
ON A.[NOME_REPRESENTANTE_LEGAL] = B.[NOME_BENEFICIARIO]

--PELO CPF
UPDATE B
SET
B.[RENDA_EMPREGO] = A.RENDA
 FROM [TEMP_VANDERLAN].[dbo].[CVP_POC Resolução CNSP 473_RENDA_v3-Dxon] B 
INNER JOIN [DX_DETALHES_CPF].[dbo].[RENDA] A
ON A.CPF = B.CPF
WHERE B.[RENDA_EMPREGO] IS NULL




