SELECT
DATAFOURLIB2010.DBO.FN_NORMALIZA([NOME_TRATADO]) AS [NOME_TRATADO],
[CPF],
[RENDA],
[NASC],
[ID_ORIGEM],
[TIPO_SERVIDOR],
DATAFOURLIB2010.DBO.FN_NORMALIZA([CIDADE/ESTADO]) AS [CIDADE/ESTADO],
DATAFOURLIB2010.DBO.FN_NORMALIZA([CARGO]) AS [CARGO],
DATAFOURLIB2010.DBO.FN_NORMALIZA([ORGAO]) AS [ORGAO],
[RENDA_FAIXA]

INTO [TEMP_VANDERLAN].[dbo].[SERVIDORES_CONSOLIDADO_OK]

FROM [TEMP_VANDERLAN].[dbo].[SERVIDORES_CONSOLIDADO];