  SELECT 
    B.NOME_SEGURADO,
    B.DATA_NASCIMENTO,
    A.CPF,
    A.NOME,
    A.DT_NASCIMENTO
FROM [TEMP_VANDERLAN].[dbo].[Relatório de segurados Odonto] B
INNER JOIN DXON_PF.dbo.PF A
    ON DATAFOURLIB2010.DBO.FN_NORMALIZA(B.NOME_SEGURADO) = A.NOME
   AND TRY_CONVERT(date, B.[DATA_NASCIMENTO], 103) 
       = TRY_CONVERT(date, A.DT_NASCIMENTO, 112)
WHERE EXISTS (
    SELECT 1
    FROM DXON_PF.dbo.PF A2
    WHERE A2.NOME = A.NOME
      AND TRY_CONVERT(date, A2.DT_NASCIMENTO, 112) 
          = TRY_CONVERT(date, B.DATA_NASCIMENTO, 103)
    GROUP BY A2.NOME, A2.DT_NASCIMENTO
    HAVING COUNT(*) > 1
)
ORDER BY B.NOME_SEGURADO;