--ALTERAR TABELAS

USE FUNCIONARIOS_PUBLICOS_MUNICIPAIS_202509

EXEC sp_rename 
    'AL_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_MACEIO_2_TRATADO.CPF',
    'CPF_INCOMPLETO',
    'COLUMN';

ALTER TABLE [FUNCIONARIOS_PUBLICOS_MUNICIPAIS_202509].[dbo].AL_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_MACEIO_2_TRATADO 
ADD CPF VARCHAR(11);

ALTER TABLE [FUNCIONARIOS_PUBLICOS_MUNICIPAIS_202509].[dbo].AL_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_MACEIO_2_TRATADO
ADD ID_ORIGEM INT NOT NULL DEFAULT 31;

ALTER TABLE [FUNCIONARIOS_PUBLICOS_MUNICIPAIS_202509].[dbo].AL_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_MACEIO_2_TRATADO
ALTER COLUMN NOME_TRATADO VARCHAR(100)
COLLATE Latin1_General_CI_AS;

ALTER TABLE [FUNCIONARIOS_PUBLICOS_MUNICIPAIS_202509].[dbo].AL_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_MACEIO_2_TRATADO
ALTER COLUMN CPF_INCOMPLETO VARCHAR(14)
COLLATE Latin1_General_CI_AS;

SELECT  * FROM
[FUNCIONARIOS_PUBLICOS_MUNICIPAIS_202509].[dbo].AL_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_MACEIO_2_TRATADO


SELECT DISTINCT ID_ORIGEM
FROM SERVIDORES_MUNICIPAIS_CONSOLIDADO
