BEGIN TRAN;

DELETE FROM [FUNCIONARIOS_PUBLICOS_ESTADUAIS_082025].[dbo].[SERVIDORES_ESTADUAIS_CONSOLIDADO]
WHERE NOME_TRATADO IS NULL;

-- Conferir resultado
SELECT COUNT(*) FROM [FUNCIONARIOS_PUBLICOS_ESTADUAIS_082025].[dbo].[SERVIDORES_ESTADUAIS_CONSOLIDADO] WHERE NOME_TRATADO IS NULL;

-- Se estiver correto:
COMMIT;

-- Se estiver errado:
-- ROLLBACK;


