USE FUNCIONARIOS_PUBLICOS_MUNICIPAIS_202509

INSERT INTO SERVIDORES_MUNICIPAIS_CONSOLIDADO 
    (NOME_TRATADO, RENDA, ID_ORIGEM)

SELECT 
    X.NOME_TRATADO,
    X.VALOR,
    X.ID_ORIGEM
FROM (
    
    SELECT NOME_TRATADO, VALOR, '37' AS ID_ORIGEM FROM AM_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_MANAUS_1_TRATADO
    UNION ALL
    SELECT NOME_TRATADO, VALOR, '38' FROM PA_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_BELEM_TRATADO
    UNION ALL
    SELECT NOME_TRATADO, VALOR, '39' FROM TO_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_PALMAS_TRATADO
    UNION ALL
    SELECT NOME_TRATADO, VALOR, '40' FROM RS_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_PORTOALEGRE_TRATADO
    UNION ALL
    SELECT NOME_TRATADO, VALOR, '41' FROM SP_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_SAOPAULO_TRATADO
    UNION ALL
    SELECT NOME_TRATADO, VALOR, '42' FROM RJ_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_RIODEJANEIRO_TRATADO
    UNION ALL
    SELECT NOME_TRATADO, VALOR, '43' FROM MG_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_BELOHORIZONTE_TRATADO
    UNION ALL
    SELECT NOME_TRATADO, VALOR, '44' FROM GO_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_GOIANIA_TRATADO
    UNION ALL
    SELECT NOME_TRATADO, VALOR, '45' FROM PR_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_CURITIBA_TRATADO
    UNION ALL
    SELECT NOME_TRATADO, VALOR, '46' FROM MS_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_CAMPOGRANDE_TRATADO
    UNION ALL
    SELECT NOME_TRATADO, VALOR, '47' FROM MT_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_CUIABA_TRATADO
    UNION ALL
    SELECT NOME_TRATADO, VALOR, '48' FROM BA_FUNCIONARIOS_PUBLICOS_MUNICIPAIS_SALVADOR_TRATADO

) X
WHERE NOT EXISTS (
    SELECT 1
    FROM SERVIDORES_MUNICIPAIS_CONSOLIDADO S
    WHERE S.NOME_TRATADO = X.NOME_TRATADO
      AND S.ID_ORIGEM = X.ID_ORIGEM
);

SELECT  *
  FROM [FUNCIONARIOS_PUBLICOS_MUNICIPAIS_202509].[dbo].[SERVIDORES_MUNICIPAIS_CONSOLIDADO ]
